### ISSUE TITLE
Provide a version for duckduckgo/other search engines?

### ISSUE THREAD

**Issue by rexendevar** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#1]
I'm not a Google user. if I want to make this list work for me I have to search and replace the term "google" on every line, which means I have to modify it and lose the ability to update it automatically from the source. Would be nice to not have to do that especially since I'm not sure how different the syntax will be for the new URLs.

**Comment by laylavish** [comment]
The uBlacklist filter should work regardless of which search engine you use, but not with the uBlockOrigin one. Currently working on getting uBO to have the same effect (it shouldn't be too hard).

**Comment by laylavish** [comment]
@rexendevar check 972d8b8086f5ab45a8e0526f791d4c4d63ee7d68 . I tested DuckDuckGo and Bing, and both seem to work fine. lmk if you see any issues! 😊

**Comment by eishiya** [comment]
Seems to be working on DuckDuckGo for me, thank you!

I looked up "aiartyapp" to check, that was something I got from the list, and a few results were hidden. I did notice one non-hidden result from a site called "centralaitools.com", that sounds like a site that should be added to the list.
