### ISSUE TITLE
Add subscribe link to README

### ISSUE THREAD

**Issue by szepeviktor** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#15]
uBlock Origin supports these links:
[subscribe link](https://subscribe.adblockplus.org?title=Huge%20AI%20Blocklist&location=https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt)

```markdown
[subscribe link](https://subscribe.adblockplus.org?title=Huge%20AI%20Blocklist&location=https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt)
```

https://github.com/gorhill/uBlock/blob/950b5ea55ea0a22af774e3b4925fbe66875981f9/src/js/scriptlets/subscriber.js#L57-L58

**Comment by szepeviktor** [comment]
Thank you.

Does it actually work?
(I do not have an adblocker)

**Comment by laylavish** [comment]
Yup, just tested with uBlock Origin & Adblock Plus.
