### ISSUE TITLE
Misinterpreted/missing feature?

### ISSUE THREAD

**Issue by DuskTheUmbreon** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#2]
[Line 936](https://github.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/blob/c0239164ce49a45e133f14971634f9add7db1aaf/list.txt#L936) of the primary list mentions the ability to press tab to comment out specific URLs.

However, I'm personally unable to get this to work. I'm unsure if there's something I'm missing, or if this was merely an internal dev comment that should be ignored. If it's intended to be a user-accessible feature and I'm simply not understanding how to utilize it, could a tutorial be added to the readme? If it's meant to be a dev comment and otherwise ignored, could that be clarified?

**Comment by laylavish** [comment]
Hey! 

I originally created this list on [pastebin](https://pastebin.com/SAriH9RZ), but then was asked to implement a subscription alternative here on GitHub. Before it became a subscription, initially you would copy & paste the text into your uBlock Origin's filter list, which would then allow you to individually tab-out (comment out) different url's that you didn't want blocked. 

That line was an artifact from bringing it over to GitHub (and i forgor about it 💀)

Now with this different implementation, you have to do it a different way.

### For uBlockOrigin: 

1. Toggle the [DOM inspector](https://github.com/gorhill/uBlock/wiki/DOM-inspector) `</>` through uBlock Origin's [logger](https://github.com/gorhill/uBlock/wiki/The-logger). 
2. Locate the url you want to whitelist. 
3. Click on the filter you want to disable (eg. vecteezy.com); it should be crossed out. 
4. Then press the save icon, then the "Create" button.

Boom! Now it's whitelisted!

Or, if you don't want to go through that mumbo-jumbo, add this line in your filter list: `www.google.com#@#a[href*="example.com"]:upward(div):style(opacity:0.00!important;)`

Change "example.com" to the url you want to whitelist. Copy & paste that in uBlock Origin's "My filters" list, and you're set!

### For uBlacklist: 
1. Enter uBlacklist's options panel. 
2. In the text box, add this line in the text box: @*://*.example.com/* 
3. Change "example.com" to a website you want whitelisted. 
4. Click save. Done!

Sorry for the hassle, and hope this works well for you! Cheers!

**Comment by DuskTheUmbreon** [comment]
Ah, I see, and that explains it. The curse of copy, paste, forgor is a devious one 😔

I do appreciate the explanation!

**Comment by laylavish** [comment]
Hi again! I added a section in the readme 12d763b523d2d8f07714744771a155754cc523dd that explains how to whitelist sites in both uBlock Origin & uBlacklist (so you don't have to reference this issue anymore). Going to close this issue since it is resolved. Have a good day! <3
