### ISSUE TITLE
uBlock rules block unrelated domains if they contain a blocked domain's name

### ISSUE THREAD

**Issue by Suyooo** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#28]
For example, the block on "udio.com" also hits "visualstudio.com", and all other domains ending with "studio.com".

Maybe it would be enough to just duplicate each rule, one prefixing the domain with a dot and one with a slash?

**Comment by Suyooo** [comment]
The block on "play.ht" also causes this issue in a slightly different way - it can hit on the filename, so any result that ends with something like "dis*play.ht*ml" is removed.

**Comment by laylavish** [comment]
Yeah, pretty unfortunate site name for sure. Doing what you suggested (duplicate the rule, one rule preceding with a forward slash and one with a period) seemed to fix it. Thanks!

**Comment by laylavish** [comment]
I think this issue has been resolved, since the prominent ones such as 'udio' & play.ht are resolved now. Unsure if there are other edge cases, but for now i'll close this issue.
