### ISSUE TITLE
"Nuclear" sites are in the main list

### ISSUE THREAD

**Issue by SBluespaniel** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#3]
I've imported the main list.txt, but now can't browse DeviantArt (specifically user profiles). I think it's because there's a "nuclear" section contained within list.txt, not just the extra addon txt file

**Comment by laylavish** [comment]
Hi! The nuclear section is in the default `list.txt` for experimental blacklists of sites (I was tired of seeing stock photography sites and wanted to see how blocking these in the main list would affect searches 61f51dcbe0b277e6882cedd211cac8ff4f608697) . If you take a look closely, some sites are commented out, meaning that they shouldn't be active. DeviantArt is commented out, and I checked myself whether or not DeviantArt pops up in image search, and it does. Can't seem to replicate what you're experiencing, so it could be an issue on your side? 

If all else fails, refer to the ReadMe and whitelist DeviantArt to see if that fixes anything.

**Comment by laylavish** [comment]
Never mind. I was wrong, and you were right. I found the issue. Weirdly, it has to do with the domain "dreamup.com" (which is deviantart's AI image generator) which is for whatever reason responsible for deviantart's user profile. Sneaky. Will fix it quickly!

**Comment by SBluespaniel** [comment]
Oh, strange!
Thank you! And thank you so much for maintaining this list - you're doing a great service!

**Comment by laylavish** [comment]
As of commit ac374f13e96469615c0417d0c976d6df4e702215 , DeviantArt user profiles should be working. And you're welcome! <3
