### ISSUE TITLE
Add aquariumfishsource.com to filter list

### ISSUE THREAD

**Issue by ngoomie** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#38]
Aquarium Fish Source is a fishkeeping content farm that has always had pretty low quality content from what I can see (they're one of those websites that take generic, broad-topic articles and rewrite them over and over and over with changes to make them specific to specific species of fish, things like lists of best aquarium heaters or lighting, just to boost their search ranking) but as of somewhat recently they've also started using AI generation for their article images, which also puts into question whether any of their recent content is human-written either, especially since the AI generated images look nothing like the fish in question, as if a human didn't even look over the result image to make sure it at least looked okay. Some examples:

From their article "Cardinal Tetra: Ultimate Care Guide For Beginners", there's [this photo](https://github.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/assets/50791600/6a57ae06-f4f0-4ea8-889e-deb9a4155ad7).
For reference, cardinal tetras actually look [like this](https://commons.wikimedia.org/wiki/File:Cardinal_Paracheirodon_axelrodi_(3).jpg).

Another one, from the article "The 21 Best Neon Tetra Tank Mates: Guides for Big Fish and 20-30 Gallon Tanks", is [this photo](https://github.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/assets/50791600/03bfde84-d8da-4638-bc50-c347e2b949bc), wherein there is a fish with no head and two tails right in the middle. Even if that wasn't an issue, while the body shape is right (for the ones that aren't missing heads), they otherwise don't look like neon tetras at all.

**Comment by laylavish** [comment]
It's added, thanks!!!
