### ISSUE TITLE
New AI websites to add

### ISSUE THREAD

**Issue by the-nullman** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#41]
hello there, I got some more AI junk to add to the blocklist.

https://civitai.com/
https://creator.nightcafe.studio/
https://www.prompthunt.com/
https://arthub.ai/
https://openart.ai/
https://aiartes.com/

(calling websites like these "open art" and "AI arts museum" is plain disgusting)

P.S. here's another one
https://www.artvy.ai/
![image](https://github.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/assets/96726090/b09037c6-34ea-499e-bf07-bb30577cbe9a)

**Comment by laylavish** [comment]
All of these are already present in the blocklist... I triple checked just to make sure. Maybe the extension is misbehaving on your end?
