### ISSUE TITLE
Unfit website

### ISSUE THREAD

**Issue by Ramiel0** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#42]
https://aquariumfishsource.com/ is listed as a website. but it doesnt seem to feature any AI content of any kind?? its just stuff about aquarium fish?
Can be found at the bottom of the 'websites with a .com extension' section

**Comment by laylavish** [comment]
Take a look at this closed issue: https://github.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/issues/38
