### ISSUE TITLE
Add talkpal.ai to list of blocked websites

### ISSUE THREAD

**Issue by ngoomie** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#43]
TalkpalAI seems to be some sort of website that provides AI-based tools to aid in language learning which also has a bunch of articles that seem to perhaps be LLM-generated, as they have hallucinated information. Some examples:

Their article "Short Stories for Learning Malay" mentions Project Gutenberg as a website that has a collection of Malay books, but if you go to their search function, they do not even have an option to filter for Malay language works (nor Indonesian ones either). The article also mentions Duolingo Stories, but Duolingo does not have a Malay course (as I recall, they have for years had a policy where two languages that are "too similar" don't get two courses, which means Malay gets considered to be more or less the same thing as Indonesian) and even Duolingo's Indonesian course does not have the Stories function.

I also found an article titled "Malay Stories to Learn Malay" which, weird-sounding title aside, is one of those low-quality types of articles that spends most of the time listing off generic and/or unhelpful information (language-agnostic tips for learning languages by reading, also a section about "the cultural significance of Malay stories") with only a small section of the article actually doing what the title implies the point to be. No immediately-obvious indication either way as to whether this one is LLM-generated or not (unless perhaps the folktales it name-dropped are hallucinated too, lmao) but it makes for a low-quality slop article anyways and it's pretty obvious it must be just based off of the general content of the website.

Just generally their content seems to be very horrifically low quality, every single blog article I even glanced at has AI-gen'd cover photos, and in their footer is actually OpenAI's logo as well as 4 pertaining to sponsorships for tech startups (nVidia Inception Program, Microsoft for Startups, Google for Startups, AWS startups)

(No articles linked just because I'm worried direct linking to them may help to boost their search rankings, but I can provide some if needed)

**Comment by laylavish** [comment]
it's added! thanks!
