### ISSUE TITLE
CoPilot?

### ISSUE THREAD

**Issue by TPS** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#45]
@laylavish I'm sorry, maybe I misunderstand this list or perhaps just simple oversight:  Shouldn't `||copilot.` be blocked?  In `hosts` syntax, it'd be 
```
0.0.0.0 copilot.microsoft.com
0.0.0.0 copilot.github.com
0.0.0.0 copilot.[insert MS domain here]
```
An MS domainlist (e.g., https://github.com/v2fly/domain-list-community/blob/master/data%2Fmicrosoft) might be helpful for the fill-in-the-blank above.

_(I suppose https://github.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/issues/29 is related to this?)_

**Comment by laylavish** [comment]
Done. That MS domain list looks useful, although it seems that copilot only operates on a single domain.

**Comment by TPS** [comment]
@laylavish GitHub has npw dedicated CoPilot domain `githubcopilot.com`, which shows up in traffic logs when logged-in browsing the website as `api.individual.githubcopilot.com`.
