### ISSUE TITLE
Add fishkeepingadvice.com to filter list

### ISSUE THREAD

**Issue by ngoomie** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#46]
This is another fishkeeping content farm that uses genAI images that are blatantly wrong, like #38 was

From their "The 15 Best Neon Tetra Tank Mates" article, [here](https://github.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/assets/50791600/21d26bfe-42b8-4ba2-ba51-7a5a3e9cfea8) is a genAI image of cherry shrimp where each "cherry shrimp" pictured has two heads and no body. The same article has other really egregious examples of shrimp in particular, like an Amano shrimp and a ghost shrimp that both look like fish bodies with shrimp heads. Another example, [the cover image](https://github.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/assets/50791600/2061a15d-211a-4330-be7f-5b0d2651023f) for "What Do Mystery Snails Eat" depicts what looks much more like a typical land snail than a mystery snail or really any freshwater aquatic snail I've personally seen.

Worth noting also: this website seems to focus primarily on betta fish care (Betta splendens specifically, since there's multiple species that get called "betta fish"), even actually selling an undoubtedly-bunkus "Betta Pro Course" for $15, and a lot of their betta fish articles have genAI images as well. But the genAI betta images are actually very good in terms of generating something that actually looks like a betta. I was thinking at first that maybe they were training their own model on images of bettas, especially since they have real photos of bettas mixed into some articles where needed (i.e. for examples of specific diseases of betta fish that affect appearance or behaviour), but one of the example genAI betta images I found when fishing up examples literally was titled `midjourney-betta-7.webp`. Probably then it's more a matter of these big models getting good enough at generating good bettas just because there happens to be lots of "good" betta-related photos with proper captions that gets scraped for inclusion in their training data sets, considering they're a very ubiquitous fish that gets commonly recommended to beginning freshwater fishkeepers. Sorry for the weird ramble lol

**Comment by laylavish** [comment]
done
