### ISSUE TITLE
https://www.vecteezy.com

### ISSUE THREAD

**Issue by stormywanderer** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#48]
This one is still showing up in google results but I dont know how to add

**Comment by laylavish** [comment]
Vecteezy is in the additional nuclear list, but I understand that additional list is not for everyone. So, here's how to add it:

## In uBlock Origin:
1. Click on the uBlock Origin extension, and hit the cog wheel symbol in the bottom right, labeled "Open the dashboard"
2. Click on the `My filters` tab
3. In one of the empty lines, copy & paste this filter in there:
```
google.com,duckduckgo.com,bing.com##a[href*="vecteezy.com"]:upward(div):style(opacity:0.00!important;)
```
4. Click `Apply Changes`
5. It's now added!

## In uBlacklist:
1. Click on the uBlacklist extension and hit the blue `Options` text
2. In the giant main text box where it says "Sites blocked from appearing in Google search results", copy and paste this filter in any empty space:

```
*://*.vecteezy.com/*
```
3. Hit the `Save` button.
4. It's now added!

Now, I've been thinking about revising the nuclear list to drop some sites such as Vecteezy, in favor of putting it in the main list instead. I've been a little bit cautious, of doing this, as Vecteezy still includes quite a bit of authentic artwork & imagery; but on the other hand, from what i've been experiencing, it seems like Vecteezy appears a lot in normal searches, and it shows their garbage AI images. So, I might put it in the main list just to test it out.

**Comment by laylavish** [comment]
Keep in mind tho, that the nuclear list really is nuclear. It takes out prominent sites such as Adobe Stock, Pixabay, Artstation, Deviantart, etc. These sites are overrun with AI spam, but even so, it still houses a lot of authentic artwork & imagery that you may want for reference. Just letting you know!
