### ISSUE TITLE
No license found

### ISSUE THREAD

**Issue by JacksonChen666** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#65]
This project does not seem to have a license declared in an obvious way, or at all. A license should be added (as this project seems to be intended as open source) so that users can run, modify, study, distribute, and use the code.

https://choosealicense.com/no-permission/

**Comment by jpsmullen** [comment]
Seconding this. I think [CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode) (public domain) would suffice, but any FOSS licence is fine.

**Comment by laylavish** [comment]
Done. I've chosen CC0.
