### ISSUE TITLE
Would filtering the Google AI Overview fit in this repo?

### ISSUE THREAD

**Issue by uwainium** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#66]
Asking before making a PR, but would adding the filter to block the Google AI overview be appropriate for the scope of this repo or is there another repo that is making effort to block that kind of thing?

**Comment by laylavish** [comment]
I think I'd like this whole repo to be a "one-size-fits-all" type of solution. I was already planning to block all onsite LLM chatbot overviews/integration anyways, so making a PR for this won't be a big deal... (although, there are already many extensions that you can download that does such a thing already...)

**Comment by Cocoiscool-531** [comment]
I know it's probably not the answer your looking for, and im not sure this could be added, but using the uBlock Origin eyedropper tool, I was able to get rid of the AI search elements without and extension, heres what was added to my filters tab:

Hope this helps someone!

```
www.google.com##.X6JNf > .s7d4ef
www.google.com##.X6JNf
```
