### ISSUE TITLE
Visual Bug?

### ISSUE THREAD

**Issue by lustfullyglancing** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#67]
I'm using UBlock Origin in Kiwibrowser, is this supposed happened or is it a visual bug? 
![Screenshot_2024-10-08-03-46-10-78_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/ba37458d-9e4e-45b7-b3ce-2f9bb436da7f)

**Comment by ShareYourHead** [comment]
The readme file on the repo says that doing it with uBlock is buggy rn. You have to use uBlacklist (idk that's available on kiwi browser)

**Comment by lustfullyglancing** [comment]
ah i see, alright then thanka
