### ISSUE TITLE
Request: pihole/adguard/NAT compatible (HOST format) list.

### ISSUE THREAD

**Issue by BIGFAAT** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#8]
Hi, thank you for your work! Like the title says it would be nice to have  HOST format lists for pihole/adguard and also NAT blocking.

Greetings!

**Comment by laylavish** [comment]
Will look into it!

**Comment by laylavish** [comment]
So, I've just created a hosts file. I currently don't have a spare computer/raspberry pi with me atm, but I tested it with my OS hosts file and it seems to work fine. Test it out and tell me how it goes! (hopefully fine!)

**Comment by BIGFAAT** [comment]
Thank you! So far i can see my adguard accepted the list without any issue and have generated 1798 rules. I will test later on a bunch of addresses before introducing further blocking on my android phone (for mobile data).

**Comment by BIGFAAT** [comment]
Work for now very well, closing this issue :)
