### ISSUE TITLE
edit preferences

### ISSUE THREAD

**Issue by japharl** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#86]
As there are multiple lists, which one is the preferred one to make edits too?

Eg: remove zavant.ai / pix.ai (both sites are down) ; add eyecandy.net (nsfw promoted by artzone.ai)

**Comment by japharl** [comment]
remove aiturbo.ai - landing page.

**Comment by japharl** [comment]
remove learnmidjourney.ai 0 403 forbidden

**Comment by japharl** [comment]
remove pisco.ai - landing page

**Comment by nobodywasishere** [comment]
Even if the websites are down, images from those websites may still show up in Google images (and the like)

**Comment by japharl** [comment]
... gotcha.  My usecase is different, but I see your point on that and will not request removals.  What file should eyecandy.net (nsfw generator) be added too then?

**Comment by nobodywasishere** [comment]
I'd recommend `noai_hosts.txt`, `list_uBlacklist.txt`, and `list.txt`

**Comment by japharl** [comment]
will create a pull request later.
